import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./main.css";
import Preloader from "@/components/Preloader";
import CustomCursor from "@/components/CustomCursor";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import SideNav from "@/components/SideNav";
import Background from "@/components/Background";
config.autoAddCss = false;

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-mont",
  weight: "500",
});

  const additionalClass = "relative custom_cursor";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${additionalClass}`}>
        <CustomCursor />
        <Preloader />
        <SideNav />
        <Background />
        {children}
      </body>
    </html>
  );
}
